package com.xptschool.teacher.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACT_TEACHER".
*/
public class ContactTeacherDao extends AbstractDao<ContactTeacher, Void> {

    public static final String TABLENAME = "CONTACT_TEACHER";

    /**
     * Properties of entity ContactTeacher.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property T_id = new Property(0, String.class, "t_id", false, "T_ID");
        public final static Property S_id = new Property(1, String.class, "s_id", false, "S_ID");
        public final static Property A_id = new Property(2, String.class, "a_id", false, "A_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Sex = new Property(4, String.class, "sex", false, "SEX");
        public final static Property Phone = new Property(5, String.class, "phone", false, "PHONE");
        public final static Property School_name = new Property(6, String.class, "school_name", false, "SCHOOL_NAME");
        public final static Property Area_name = new Property(7, String.class, "area_name", false, "AREA_NAME");
    };


    public ContactTeacherDao(DaoConfig config) {
        super(config);
    }
    
    public ContactTeacherDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACT_TEACHER\" (" + //
                "\"T_ID\" TEXT," + // 0: t_id
                "\"S_ID\" TEXT," + // 1: s_id
                "\"A_ID\" TEXT," + // 2: a_id
                "\"NAME\" TEXT," + // 3: name
                "\"SEX\" TEXT," + // 4: sex
                "\"PHONE\" TEXT," + // 5: phone
                "\"SCHOOL_NAME\" TEXT," + // 6: school_name
                "\"AREA_NAME\" TEXT);"); // 7: area_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT_TEACHER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContactTeacher entity) {
        stmt.clearBindings();
 
        String t_id = entity.getT_id();
        if (t_id != null) {
            stmt.bindString(1, t_id);
        }
 
        String s_id = entity.getS_id();
        if (s_id != null) {
            stmt.bindString(2, s_id);
        }
 
        String a_id = entity.getA_id();
        if (a_id != null) {
            stmt.bindString(3, a_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(5, sex);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
 
        String school_name = entity.getSchool_name();
        if (school_name != null) {
            stmt.bindString(7, school_name);
        }
 
        String area_name = entity.getArea_name();
        if (area_name != null) {
            stmt.bindString(8, area_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContactTeacher entity) {
        stmt.clearBindings();
 
        String t_id = entity.getT_id();
        if (t_id != null) {
            stmt.bindString(1, t_id);
        }
 
        String s_id = entity.getS_id();
        if (s_id != null) {
            stmt.bindString(2, s_id);
        }
 
        String a_id = entity.getA_id();
        if (a_id != null) {
            stmt.bindString(3, a_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(5, sex);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(6, phone);
        }
 
        String school_name = entity.getSchool_name();
        if (school_name != null) {
            stmt.bindString(7, school_name);
        }
 
        String area_name = entity.getArea_name();
        if (area_name != null) {
            stmt.bindString(8, area_name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ContactTeacher readEntity(Cursor cursor, int offset) {
        ContactTeacher entity = new ContactTeacher( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // t_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // s_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // a_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sex
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // phone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // school_name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // area_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContactTeacher entity, int offset) {
        entity.setT_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setS_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setA_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSex(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPhone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSchool_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setArea_name(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ContactTeacher entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ContactTeacher entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
