package com.xptschool.parent.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEAN_CHAT".
*/
public class BeanChatDao extends AbstractDao<BeanChat, String> {

    public static final String TABLENAME = "BEAN_CHAT";

    /**
     * Properties of entity BeanChat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ChatId = new Property(0, String.class, "chatId", true, "CHAT_ID");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Size = new Property(2, int.class, "size", false, "SIZE");
        public final static Property ParentId = new Property(3, String.class, "parentId", false, "PARENT_ID");
        public final static Property TeacherId = new Property(4, String.class, "teacherId", false, "TEACHER_ID");
        public final static Property FileName = new Property(5, String.class, "fileName", false, "FILE_NAME");
        public final static Property Seconds = new Property(6, String.class, "seconds", false, "SECONDS");
        public final static Property Content = new Property(7, String.class, "content", false, "CONTENT");
        public final static Property IsSend = new Property(8, boolean.class, "isSend", false, "IS_SEND");
        public final static Property SendStatus = new Property(9, int.class, "sendStatus", false, "SEND_STATUS");
        public final static Property Time = new Property(10, String.class, "time", false, "TIME");
        public final static Property HasRead = new Property(11, boolean.class, "hasRead", false, "HAS_READ");
    };


    public BeanChatDao(DaoConfig config) {
        super(config);
    }
    
    public BeanChatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEAN_CHAT\" (" + //
                "\"CHAT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: chatId
                "\"TYPE\" TEXT," + // 1: type
                "\"SIZE\" INTEGER NOT NULL ," + // 2: size
                "\"PARENT_ID\" TEXT," + // 3: parentId
                "\"TEACHER_ID\" TEXT," + // 4: teacherId
                "\"FILE_NAME\" TEXT," + // 5: fileName
                "\"SECONDS\" TEXT," + // 6: seconds
                "\"CONTENT\" TEXT," + // 7: content
                "\"IS_SEND\" INTEGER NOT NULL ," + // 8: isSend
                "\"SEND_STATUS\" INTEGER NOT NULL ," + // 9: sendStatus
                "\"TIME\" TEXT," + // 10: time
                "\"HAS_READ\" INTEGER NOT NULL );"); // 11: hasRead
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEAN_CHAT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BeanChat entity) {
        stmt.clearBindings();
 
        String chatId = entity.getChatId();
        if (chatId != null) {
            stmt.bindString(1, chatId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getSize());
 
        String parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindString(4, parentId);
        }
 
        String teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindString(5, teacherId);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(6, fileName);
        }
 
        String seconds = entity.getSeconds();
        if (seconds != null) {
            stmt.bindString(7, seconds);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
        stmt.bindLong(9, entity.getIsSend() ? 1L: 0L);
        stmt.bindLong(10, entity.getSendStatus());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(11, time);
        }
        stmt.bindLong(12, entity.getHasRead() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BeanChat entity) {
        stmt.clearBindings();
 
        String chatId = entity.getChatId();
        if (chatId != null) {
            stmt.bindString(1, chatId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
        stmt.bindLong(3, entity.getSize());
 
        String parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindString(4, parentId);
        }
 
        String teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindString(5, teacherId);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(6, fileName);
        }
 
        String seconds = entity.getSeconds();
        if (seconds != null) {
            stmt.bindString(7, seconds);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(8, content);
        }
        stmt.bindLong(9, entity.getIsSend() ? 1L: 0L);
        stmt.bindLong(10, entity.getSendStatus());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(11, time);
        }
        stmt.bindLong(12, entity.getHasRead() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BeanChat readEntity(Cursor cursor, int offset) {
        BeanChat entity = new BeanChat( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // chatId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.getInt(offset + 2), // size
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // parentId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // teacherId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fileName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // seconds
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // content
            cursor.getShort(offset + 8) != 0, // isSend
            cursor.getInt(offset + 9), // sendStatus
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // time
            cursor.getShort(offset + 11) != 0 // hasRead
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BeanChat entity, int offset) {
        entity.setChatId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSize(cursor.getInt(offset + 2));
        entity.setParentId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTeacherId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFileName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSeconds(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setContent(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsSend(cursor.getShort(offset + 8) != 0);
        entity.setSendStatus(cursor.getInt(offset + 9));
        entity.setTime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setHasRead(cursor.getShort(offset + 11) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(BeanChat entity, long rowId) {
        return entity.getChatId();
    }
    
    @Override
    public String getKey(BeanChat entity) {
        if(entity != null) {
            return entity.getChatId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
